# Generated by Django 4.1.1 on 2022-10-06 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userdata_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='user_group',
        ),
    ]
