# Generated by Django 4.1.1 on 2022-10-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_userdata_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='photoURL',
            field=models.CharField(default='assets/images/avatars/brian-hughes.jpg', max_length=100),
        ),
    ]
